### ISSUE TITLE
pyparadox update for 2018

### ISSUE THREAD

**Issue by ghost** [grigoryvp/pyparadox#1]
would it be very difficult to update again? or is the project dead?
I'm thinking of seeing the code and creating a link to tyranny, hoi4 and Pillars of Eternity
my only doubt would be in relation to this

`[anastiel@anastiel-pc ~]$ pyparadox stellaris
2017-12-25 20:57:03,200 - pyparadox.config - WARNING - /home/anastiel/.config/PyParadox/pyparadox_stellaris.json not found, using default
[anastiel@anastiel-pc ~]$ [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
`
Is this just above common?
and did not generate any folders in .config 
thanks support

**Comment by grigoryvp** [comment]
The lib is about "Paradox" database file format, not "Paradox Interactive" games :)
